# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-21

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Non-transitive R class
android.nonTransitiveRClass=true

# Compose
android.defaults.buildfeatures.buildconfig=true
